# .travis.yml
dist: precise

language: php

php:
  - 7.2

addons:
  mariadb: 10.4
  sonarcloud:
    organization: vlad-ko_app-stripe-test

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - cp .env.travis .env
  - sudo mysql -e 'CREATE DATABASE testing;'
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --no-interaction -vvv

script:
  - vendor/bin/phpunit --coverage-clover 'clover.xml'

after_success:
    - bash  <(curl -s https://codecov.io/bash) -f clover.xml